import { NextResponse } from "next/server";

const segments = [
  {
    key: "champions",
    name: "Champions",
    count: 145,
    percentage: 18.5,
    demographics: "Mayoritas petani pemilik lahan luas & wiraswasta desa (Usia 35–50)",
    avgTransaction: 1_850_000,
    avgRecency: 2,
    rfmScore: "RFM: 5-5-5",
    color: "#16a34a",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
    iconColor: "text-emerald-600",
    icon: "military_tech",
    members: [
      { id: "A-001", name: "Budi Santoso", recency: 1, frequency: 48, monetary: 2_400_000, lastTransaction: "08 Jul 2026" },
      { id: "A-002", name: "Siti Rahayu", recency: 2, frequency: 52, monetary: 1_980_000, lastTransaction: "07 Jul 2026" },
      { id: "A-003", name: "Darmawan", recency: 3, frequency: 45, monetary: 2_100_000, lastTransaction: "06 Jul 2026" },
      { id: "A-004", name: "Endah Kurniasih", recency: 1, frequency: 60, monetary: 2_750_000, lastTransaction: "08 Jul 2026" },
      { id: "A-005", name: "Prasetyo", recency: 4, frequency: 41, monetary: 1_650_000, lastTransaction: "05 Jul 2026" },
    ],
    recommendations: {
      marketing: "Tawarkan program VIP preorder untuk komoditas premium dan diskon khusus grosir.",
      product: "Berikan akses awal untuk alat mesin pertanian (alsintan) teknologi terbaru.",
      pricing: "Berikan program loyalitas rebate (cashback SHU tambahan) di akhir tahun buku.",
      credit: "Tingkatkan limit kredit mikro tanpa jaminan fisik hingga Rp 15 Juta.",
      relationship: "Tunjuk sebagai perwakilan komite anggota dalam rapat pleno koperasi.",
    },
  },
  {
    key: "loyal",
    name: "Loyal Members",
    count: 198,
    percentage: 25.2,
    demographics: "Ibu rumah tangga aktif & buruh tani (Usia 25–45)",
    avgTransaction: 920_000,
    avgRecency: 5,
    rfmScore: "RFM: 4-5-4",
    color: "#2563eb",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    iconColor: "text-blue-600",
    icon: "star",
    members: [
      { id: "B-011", name: "Wati Suryani", recency: 3, frequency: 38, monetary: 980_000, lastTransaction: "06 Jul 2026" },
      { id: "B-012", name: "Ngatirah", recency: 5, frequency: 36, monetary: 870_000, lastTransaction: "04 Jul 2026" },
      { id: "B-013", name: "Mimin Hartini", recency: 4, frequency: 40, monetary: 1_020_000, lastTransaction: "05 Jul 2026" },
      { id: "B-014", name: "Slamet Riyadi", recency: 6, frequency: 33, monetary: 890_000, lastTransaction: "03 Jul 2026" },
      { id: "B-015", name: "Tukiyem", recency: 5, frequency: 37, monetary: 950_000, lastTransaction: "04 Jul 2026" },
    ],
    recommendations: {
      marketing: "Kirimkan brosur bundling mingguan kebutuhan pokok rumah tangga via WhatsApp.",
      product: "Fokuskan pada produk sembako berkualitas dengan harga stabil.",
      pricing: "Gunakan fixed pricing dengan garansi harga termurah se-kecamatan.",
      credit: "Berikan fasilitas cicilan kredit belanja harian dengan tenor 30 hari.",
      relationship: "Berikan apresiasi bingkisan sembako gratis pada peringatan hari koperasi.",
    },
  },
  {
    key: "potential",
    name: "Potential Loyalist",
    count: 110,
    percentage: 14.0,
    demographics: "Pemuda desa produktif & peternak mandiri (Usia 20–35)",
    avgTransaction: 750_000,
    avgRecency: 12,
    rfmScore: "RFM: 3-3-3",
    color: "#d97706",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
    iconColor: "text-amber-600",
    icon: "trending_up",
    members: [
      { id: "C-021", name: "Andi Firmansyah", recency: 10, frequency: 18, monetary: 780_000, lastTransaction: "29 Jun 2026" },
      { id: "C-022", name: "Rudi Hermanto", recency: 14, frequency: 15, monetary: 720_000, lastTransaction: "25 Jun 2026" },
      { id: "C-023", name: "Lina Setianingsih", recency: 11, frequency: 20, monetary: 810_000, lastTransaction: "28 Jun 2026" },
      { id: "C-024", name: "Agus Purwanto", recency: 8, frequency: 22, monetary: 690_000, lastTransaction: "01 Jul 2026" },
      { id: "C-025", name: "Dewi Astuti", recency: 12, frequency: 17, monetary: 750_000, lastTransaction: "27 Jun 2026" },
    ],
    recommendations: {
      marketing: "Kampanyekan program referral anggota berhadiah saldo belanja digital.",
      product: "Sediakan produk pakan ternak konsentrat dan vitamin hewan peliharaan.",
      pricing: "Tawarkan bundling 'Beli 5 Gratis 1' untuk produk pertanian pilihan.",
      credit: "Fasilitasi modal usaha bergulir plafon rendah dengan pendampingan.",
      relationship: "Undang ke forum pelatihan digital marketing untuk UMKM desa.",
    },
  },
  {
    key: "at_risk",
    name: "At Risk",
    count: 98,
    percentage: 12.5,
    demographics: "Petani musiman & buruh harian (Usia 30–55)",
    avgTransaction: 480_000,
    avgRecency: 35,
    rfmScore: "RFM: 2-4-3",
    color: "#ea580c",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    iconColor: "text-orange-600",
    icon: "warning",
    members: [
      { id: "D-031", name: "Karno Wiyoto", recency: 32, frequency: 24, monetary: 510_000, lastTransaction: "07 Jun 2026" },
      { id: "D-032", name: "Sri Mulyati", recency: 38, frequency: 22, monetary: 450_000, lastTransaction: "01 Jun 2026" },
      { id: "D-033", name: "Parno", recency: 30, frequency: 26, monetary: 490_000, lastTransaction: "09 Jun 2026" },
      { id: "D-034", name: "Yuyun Kurniasih", recency: 40, frequency: 20, monetary: 420_000, lastTransaction: "29 May 2026" },
      { id: "D-035", name: "Sukir", recency: 35, frequency: 23, monetary: 470_000, lastTransaction: "04 Jun 2026" },
    ],
    recommendations: {
      marketing: "Kirimkan pesan personal WA berisi penawaran eksklusif 'Selamat datang kembali'.",
      product: "Hubungi langsung via telepon untuk memahami kebutuhan terkini mereka.",
      pricing: "Berikan diskon retensi 15% untuk transaksi pertama setelah kembali aktif.",
      credit: "Tawarkan restrukturisasi cicilan jika ada tunggakan mikro.",
      relationship: "Kunjungan langsung oleh pengurus koperasi untuk menjaga hubungan.",
    },
  },
  {
    key: "lost",
    name: "Lost Members",
    count: 77,
    percentage: 9.8,
    demographics: "Anggota lama tidak aktif (Usia 40+)",
    avgTransaction: 220_000,
    avgRecency: 90,
    rfmScore: "RFM: 1-1-1",
    color: "#dc2626",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    iconColor: "text-red-600",
    icon: "person_off",
    members: [
      { id: "E-041", name: "Marsono", recency: 85, frequency: 5, monetary: 230_000, lastTransaction: "15 Apr 2026" },
      { id: "E-042", name: "Rusmiyati", recency: 95, frequency: 3, monetary: 180_000, lastTransaction: "05 Apr 2026" },
      { id: "E-043", name: "Sarwono", recency: 102, frequency: 4, monetary: 210_000, lastTransaction: "29 Mar 2026" },
      { id: "E-044", name: "Tumini", recency: 88, frequency: 6, monetary: 260_000, lastTransaction: "12 Apr 2026" },
      { id: "E-045", name: "Gimin", recency: 110, frequency: 2, monetary: 150_000, lastTransaction: "20 Mar 2026" },
    ],
    recommendations: {
      marketing: "Kirimkan surat fisik berisi penawaran reaktivasi keanggotaan dengan insentif.",
      product: "Survey kebutuhan mereka melalui kunjungan langsung ke rumah.",
      pricing: "Tawarkan program 'Mulai Lagi' dengan harga khusus pemula.",
      credit: "Hapus tunggakan kecil sebagai goodwill untuk mendorong reaktivasi.",
      relationship: "Undang ke acara sosial koperasi tanpa tekanan transaksi.",
    },
  },
  {
    key: "new",
    name: "New Members",
    count: 157,
    percentage: 20.0,
    demographics: "Anggota baru bergabung < 3 bulan (Semua usia)",
    avgTransaction: 340_000,
    avgRecency: 8,
    rfmScore: "RFM: 5-1-1",
    color: "#7c3aed",
    bgColor: "bg-violet-50",
    borderColor: "border-violet-200",
    iconColor: "text-violet-600",
    icon: "person_add",
    members: [
      { id: "F-051", name: "Rahayu Ningsih", recency: 5, frequency: 3, monetary: 360_000, lastTransaction: "04 Jul 2026" },
      { id: "F-052", name: "Hendra Kusuma", recency: 9, frequency: 2, monetary: 290_000, lastTransaction: "30 Jun 2026" },
      { id: "F-053", name: "Nurul Aini", recency: 7, frequency: 4, monetary: 410_000, lastTransaction: "02 Jul 2026" },
      { id: "F-054", name: "Bambang Triyono", recency: 6, frequency: 3, monetary: 320_000, lastTransaction: "03 Jul 2026" },
      { id: "F-055", name: "Fitri Handayani", recency: 10, frequency: 2, monetary: 270_000, lastTransaction: "29 Jun 2026" },
    ],
    recommendations: {
      marketing: "Berikan welcome pack berisi voucher belanja Rp 25.000 untuk transaksi pertama.",
      product: "Perkenalkan seluruh lini produk melalui katalog digital interaktif.",
      pricing: "Harga pengenalan khusus 'anggota baru' untuk 3 transaksi pertama.",
      credit: "Edukasi tentang fasilitas pinjaman mikro dan mekanisme SHU koperasi.",
      relationship: "Orientasi virtual koperasi dan perkenalan dengan pengurus utama.",
    },
  },
];

export async function GET() {
  return NextResponse.json({ success: true, segments });
}
